/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./../components/layout/header/index.vue')['default']
    HeaderActions: typeof import('./../components/layout/header/header-actions.vue')['default']
    Left: typeof import('./../components/layout/sidebar/left/index.vue')['default']
    Right: typeof import('./../components/layout/sidebar/right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./../components/layout/sidebar/left/search-dialog.vue')['default']
    SidebarItem: typeof import('../components/layout/sidebar/left/sidebar-main-items.vue')['default']
    SidebarMainItems: typeof import('./../components/layout/sidebar/left/sidebar-main-items.vue')['default']
    SidebarNoteContextMenu: typeof import('./../components/layout/sidebar/left/sidebar-note-context-menu.vue')['default']
    SidebarNoteItem: typeof import('./../components/layout/sidebar/left/sidebar-note-item.vue')['default']
    SidebarNoteItems: typeof import('./../components/layout/sidebar/left/sidebar-note-items.vue')['default']
    SidebarNoteTree: typeof import('./../components/layout/sidebar/left/sidebar-note-tree.vue')['default']
    SidebarSearchbar: typeof import('./../components/layout/sidebar/left/sidebar-searchbar.vue')['default']
    TestSettings: typeof import('./../views/test-settings.vue')['default']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCommandPalette: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UDropdownMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UModal: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USeparator: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap_97835f79590fea2a6ea97161f2f50c6b/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    Versions: typeof import('./../components/Versions.vue')['default']
    Views: typeof import('./../views/index.vue')['default']
  }
}
